let requiredClausesMultiple = [
    ["and", [["where"]]],
    ["asc", [["order by"]]],
    ["between", [["where"]]],
    ["cross", [["join"]]],
    ["desc", [["order by"]]],
    ["distinct", [["select"]]],
    ["duplicate", [["insert"]]],
    ["from", [["select"], ["delete"]]],
    ["group", [["by"]]],
    ["group", [["from"]]],
    ["having", [["group by"]]],
    ["in", [["where"]]],
    ["inner", [["join"]]],
    ["insert", [["into"]]],
    ["insert", [["value"], ["values"]]],
    ["intersect", [["select"]]],
    ["into", [["insert"]]],
    ["into", [["values"], ["value"]]],
    ["join", [[" on"]]],
    ["join", [["from"], ["update"]]],
    ["left", [["join"]]],
    ["like", [["where"]]],
    ["limit", [["from"], ["select"], ["update"]]],
    ["minus", [["select"]]],
    ["on", [["join"]]],
    ["or", [["where"]]],
    ["order", [["by"]]],
    ["order", [["from"]]],
    ["outer", [["join"]]],
    ["right", [["join"]]],
    ["rollup", [["group by"], ["with"]]],
    ["select", [["from"]]],
    ["set", [["insert"], ["update"]]],
    ["union", [["select"]]],
    ["update", [["set"]]],
    ["value", [["insert"]]],
    ["values", [["insert"]]],
    ["where", [["from"], ["update"]]]
];